### ISSUE TITLE
Ubuntu + Numpy > 2.0 cause ALMA POLARIZATION::CORR_TYPE to be unloadable

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/xradio#242]
When using Ubuntu + Numpy > 2.0 all the ALMA-related tests fail with being unable to load the POLARIZATION::CORR_TYPE column. It is of type int instead of record. 

- The tests pass on MacOS with Numpy > 2.0. 
- In the pyproject.toml numpy<2.0.0 for the meantime.
- Error message: "Table DataManager error: Internal error: StManIndArray::get/put shapes not conforming"
- Tests giving the error (https://github.com/casangi/xradio/actions/runs/10690640769/job/29635731926):

```
FAILED tests/stakeholder/test_vis_stakeholder.py::test_alma - KeyError: "No variable named 'CORR_TYPE'. Variables on the dataset include ['FLAG_ROW', 'NUM_CORR']"
FAILED tests/stakeholder/test_vis_stakeholder.py::test_ephemeris - KeyError: "No variable named 'CORR_TYPE'. Variables on the dataset include ['FLAG_ROW', 'NUM_CORR']"
FAILED tests/stakeholder/test_vis_stakeholder.py::test_alma_ephemeris_mosaic - KeyError: "No variable named 'CORR_TYPE'. Variables on the dataset include ['FLAG_ROW', 'NUM_CORR']"
FAILED tests/stakeholder/test_vis_stakeholder.py::test_sd_A002_X1015532_X1926f - KeyError: "No variable named 'CORR_TYPE'. Variables on the dataset include ['FLAG_ROW', 'NUM_CORR']"
FAILED tests/stakeholder/test_vis_stakeholder.py::test_sd_A002_Xced5df_Xf9d9 - KeyError: "No variable named 'CORR_TYPE'. Variables on the dataset include ['FLAG_ROW', 'NUM_CORR']"
FAILED tests/stakeholder/test_vis_stakeholder.py::test_sd_A002_Xe3a5fd_Xe38e - KeyError: "No variable named 'CORR_TYPE'. Variables on the dataset include ['FLAG_ROW', 'NUM_CORR']"
FAILED tests/unit/vis/_vis_utils/test_ms.py::test_read_alma_ms_default - AttributeError: 'Dataset' object has no attribute 'CORR_TYPE'
FAILED tests/unit/vis/_vis_utils/test_ms.py::test_read_alma_ms_by_ddi - AttributeError: 'Dataset' object has no attribute 'CORR_TYPE'
```

**Comment by FedeMPouzols** [comment]
At first look this might have to do with interger sizes (32/64) after the casacore + numpy upgrade:
```
WARNING  xradio:logger.py:109 Antennae_North.cal.lsrk.split.ms/POLARIZATION: failed to load data for column CORR_TYPE: Python integer -9223372036854775808 out of bounds for int32
WARNING  xradio:logger.py:109 Antennae_North.cal.lsrk.split.ms/POLARIZATION: failed to load data for column CORR_PRODUCT: Python integer -9223372036854775808 out of bounds for int32
WARNING  xradio:logger.py:109 Antennae_North.cal.lsrk.split.ms/POLARIZATION: failed to load data for column CORR_TYPE: Python integer -9223372036854775808 out of bounds for int32
WARNING  xradio:logger.py:109 Antennae_North.cal.lsrk.split.ms/POLARIZATION: failed to load data for column CORR_PRODUCT: Python integer -9223372036854775808 out of bounds for int32
```
So this probably interacts with #219 (nearly finished) and hopefully there is a tidy way to address both issues at the same time.
That also makes me suspect that the Mac builds are passing but getting bogus 0s in those missing cells.

**Comment by FedeMPouzols** [comment]
With Python 3.9 the issue is not there (uses numpy up to 2.0.2 - after 2.1.x numpy dropped support for Python 3.9). numpy 2.1.x seems to introduce the problem and I can reproduce it locally with Python 3.10 + numpy 2.1.1, and with Python 3.12 + numpy 2.1.1. Strangely enough I'm getting many additional errors related to `StringDType` and `_NoValueType` which do not seem to trigger in the CI builds.

**Comment by FedeMPouzols** [comment]
Finally I think I have some fuzzy understanding of what is happening. Casacore gives as type 'int' in the CORR_TYPE column description. But because this is a variable size column with irregular array lengths, we use the tablerow tool of python-casacore. tablerow returns rows like this;
```
row={'CORR_TYPE': array([ 9, 12], dtype=int32), 'CORR_PRODUCT': array([[0, 0],
       [1, 1]], dtype=int32), 'FLAG_ROW': False, 'NUM_CORR': 2}
row={'CORR_TYPE': array([1], dtype=int32), 'CORR_PRODUCT': array([[0, 0]], dtype=int32), 'FLAG_ROW': False, 'NUM_CORR': 1}
```
It seems numpy 2 has become more explicit about these int size discrepancies (int32 what tablerow actually returns vs. int==int64 what we were taking from the column description).
